# Generated by Django 6.0.2 on 2026-04-02 18:46

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(help_text='user, assistant, or system', max_length=20)),
                ('content', models.TextField(help_text='Content shown to frontend')),
                ('raw_content', models.TextField(blank=True, help_text='Full LLM response with hidden tags (debug only)', null=True)),
                ('token_count', models.IntegerField(default=0, help_text='Token count for this individual message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rpg_chat_logs',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CharacterImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('clothes', models.CharField(help_text='e.g. suit, daily', max_length=50)),
                ('emotion', models.CharField(help_text='e.g. happy, sad, thinking', max_length=50)),
                ('image_url', models.CharField(help_text='S3 or CDN path', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rpg_character_images',
                'unique_together': {('clothes', 'emotion')},
            },
        ),
        migrations.CreateModel(
            name='Lorebook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), help_text='Lorebook trigger keywords')),
                ('lorebook', models.TextField(help_text='Lorebook prompt content')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rpg_lorebooks',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['keywords'], name='idx_rpg_lorebooks_keywords')],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_nickname', models.CharField(help_text='Nickname entered at game start', max_length=50)),
                ('status_window_enabled', models.BooleanField(default=True, help_text='Toggle for status window display')),
                ('total_tokens', models.IntegerField(default=0, help_text='Running cumulative token count for hypermemory trigger')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpg_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rpg_sessions',
            },
        ),
        migrations.CreateModel(
            name='MessageEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('chunk_content', models.TextField(help_text='Source text chunk (KSS-split sentence)')),
                ('chat_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='rpg.chatlog')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_embeddings', to='rpg.session')),
            ],
            options={
                'db_table': 'rpg_message_embeddings',
            },
        ),
        migrations.CreateModel(
            name='HyperMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.TextField(blank=True, null=True)),
                ('in_game_date', models.DateField(blank=True, null=True)),
                ('in_game_time', models.TimeField(blank=True, null=True)),
                ('location_transition', models.TextField(blank=True, help_text='e.g. 탕비실 → 회의실', null=True)),
                ('characters_present', models.JSONField(blank=True, help_text='e.g. ["강하리", "민제", "팀장님"]', null=True)),
                ('context_overview', models.TextField(blank=True, help_text='Story summary', null=True)),
                ('events', models.JSONField(blank=True, help_text='List of events/actions', null=True)),
                ('infos', models.JSONField(blank=True, help_text='Newly learned facts/settings', null=True)),
                ('emotional_dynamics', models.TextField(blank=True, help_text='Emotion/relationship/tension', null=True)),
                ('dialogues', models.JSONField(blank=True, help_text='e.g. [{"speaker": "하리", "line": "..."}]', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_msg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hyper_memories', to='rpg.chatlog')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hyper_memories', to='rpg.session')),
            ],
            options={
                'db_table': 'rpg_hyper_memories',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatlog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_logs', to='rpg.session'),
        ),
        migrations.CreateModel(
            name='StoryProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chapter', models.IntegerField()),
                ('transitioned_at', models.DateTimeField(auto_now_add=True, help_text='When this chapter was reached')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_progress', to='rpg.session')),
            ],
            options={
                'db_table': 'rpg_story_progress',
                'ordering': ['transitioned_at'],
            },
        ),
    ]
